version: '3.6'
services:
  api:
    build: .
    ports:
      - "8001:8001"
    networks:
      - test
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: nam1ahai
    networks:
      - test
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://postgres:nam1ahai@postgres:5432/postgres
      PG_DATABASE_URL: postgresql://postgres:nam1ahai@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    networks:
      - test
volumes:
  db_data:
networks:
  test:
    driver: bridge